---
name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  servers:
    name: Servers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Run build
        run: ./build.sh
        continue-on-error: false
      - name: Run delivery
        run: ./delivery.sh
        continue-on-error: false
